language: php
sudo: false
git:
    depth: 1
script: phpunit

matrix:
  fast_finish: true
  include:
    # bleeding edge (unreleased dev versions where failures are allowed)
    - php: nightly
      env: SYMFONY_VERSION="dev-master"
    # stable (most recent stable versions)
    - php: 7.1
      env:
        - SYMFONY_VERSION="3.2.*"
        - TWIG_VERSION="2.x-dev"
        - CHECK_PHP_SYNTAX="yes"
    # common (some popular version combinations)
    - php: 7.0
      env: SYMFONY_VERSION="3.1.*"
    # common (some popular version combinations)
    - php: 5.6
      env:
        - SYMFONY_VERSION="2.8.*"
        - ENABLE_CODE_COVERAGE="true"
    # legacy (oldest supported versions)
    - php: 5.3
      env:
        - SYMFONY_VERSION="2.3.*"
        - COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly
    # code coverage is very slow; allow a failure to get the Travis result early
    - env:
        - SYMFONY_VERSION="2.8.*"
        - ENABLE_CODE_COVERAGE="true"


install:
  -  composer update --prefer-dist --no-interaction --no-suggest --no-progress --ansi

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;